### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by benhalverson** [benhalverson/react-budget-app#10]
File                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------------|----------|----------|----------|----------|-------------------|
All files                 |    61.01 |    77.63 |    63.74 |    58.97 |                   |
 src                      |      6.9 |        0 |        0 |      6.9 |                   |
  App.js                  |        0 |      100 |        0 |        0 |1,2,3,4,5,6,7,8,11 |
  index.js                |        0 |        0 |        0 |        0 |... 17,18,19,20,21 |
  setupTests.js           |      100 |      100 |      100 |      100 |                   |
 src/__fixtures__         |      100 |      100 |      100 |      100 |                   |
  expenses.js             |      100 |      100 |      100 |      100 |                   |
  filters.js              |      100 |      100 |      100 |      100 |                   |
 src/actions              |       75 |     62.5 |    65.22 |    67.74 |                   |
  expenses.js             |    66.67 |    57.14 |    55.56 |    61.54 |... 68,69,70,71,77 |
  filters.js              |      100 |      100 |      100 |      100 |                   |
 src/components           |    69.15 |    86.67 |       60 |    70.37 |                   |
  CreateExpensePage.js    |    66.67 |      100 |       50 |       80 |                24 |
  EditExpensePage.js      |    58.33 |      100 |     37.5 |       70 |          29,33,34 |
  ErrorBoundary.js        |        0 |        0 |        0 |        0 |  1,4,5,9,13,15,17 |
  ExpenseDashboardPage.js |      100 |      100 |      100 |      100 |                   |
  ExpenseForm.js          |    96.15 |       95 |    93.75 |    94.74 |                82 |
  ExpenseList.js          |       80 |      100 |    66.67 |       80 |                19 |
  ExpenseListFilters.js   |       60 |       75 |    42.86 |    64.71 | 56,70,71,72,73,74 |
  ExpenseListItem.js      |      100 |      100 |      100 |      100 |                   |
  ExpensesSummary.js      |    71.43 |      100 |       50 |    71.43 |             30,31 |
  Header.js               |      100 |      100 |      100 |      100 |                   |
  HelpPage.js             |        0 |      100 |        0 |        0 |             1,2,3 |
  NotFoundPage.js         |      100 |      100 |      100 |      100 |                   |
 src/firebase             |      100 |      100 |      100 |      100 |                   |
  firebase.js             |      100 |      100 |      100 |      100 |                   |
 src/reducers             |    94.74 |    93.33 |      100 |    94.44 |                   |
  expenses.js             |    90.91 |     87.5 |      100 |       90 |                24 |
  filters.js              |      100 |      100 |      100 |      100 |                   |
 src/routers              |        0 |      100 |        0 |        0 |                   |
  AppRouter.js            |        0 |      100 |        0 |        0 |... ,6,7,8,9,10,11 |
 src/selectors            |      100 |    93.33 |      100 |      100 |                   |
  expenses-total.js       |      100 |      100 |      100 |      100 |                   |
  expenses.js             |      100 |    93.33 |      100 |      100 |                16 |
 src/store                |        0 |        0 |      100 |        0 |                   |
  configureStore.js       |        0 |        0 |      100 |        0 |    1,2,3,4,6,8,16 |

**Comment by Dikaeinstein** [comment]
@benhalverson Do you want to increase the test coverage? If yes, then I can handle it

**Comment by benhalverson** [comment]
@Dikaeinstein yes if you can do it 👍 thanks for the help.

**Comment by Dikaeinstein** [comment]
@benhalverson I'm done. [PR](https://github.com/benhalverson/react-budget-app/pull/11) is up for the issue.
