### ISSUE TITLE
Add material design UI

### ISSUE THREAD

**Issue by benhalverson** [benhalverson/react-budget-app#101]
Make the app pretty...
Use material design bootstrap or something similar...

**Comment by dbeigi** [comment]
Hi, @benhalverson I would like to help you. Got any suggestions or ideas?

**Comment by benhalverson** [comment]
@dbeigi um not off the top of my head. Maybe use some cards https://material.io/components/cards/ I have the title and description but I'm only using the title right now in the UI.

**Comment by dbeigi** [comment]
@benhalverson It seems like I need the API keys to run the application. Getting this firebase error:

> Error: FIREBASE FATAL ERROR: Can't determine Firebase Database URL.  Be sure to include databaseURL option when calling firebase.initializeApp().

**Comment by benhalverson** [comment]
@dbeigi Yes you will need to create your own keys from firebase and put them in `.env.development` Follow the `.env.sample` file
