### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by benhalverson** [benhalverson/react-budget-app#5]
Pick a CSS framework

**Comment by brentrobbins** [comment]
Hi @benhalverson,
If you are trying to keep thing lightweight you might want to try Bulma is a modern CSS framework based on Flexbox (it's just CSS and no JS). 

To get started you install: [react-bulma-components](https://github.com/couds/react-bulma-components) [bluma](https://github.com/jgthms/bulma) npm packages.

Hope that helps and it not let me know your criteria. 

Please let me know if you have any questions.
Thanks,
Brent

**Comment by benhalverson** [comment]
Hi @brentrobbins thanks for sharing. I'll take a look at Bluma. Are you a contributor / maintainer for the project?

**Comment by brentrobbins** [comment]
@benhalverson No, I was looking a month or two ago for the same thing and found it and really like how it's setup (use all sass or just import the features you want, flexbox based and no js). I should probably consider contributing...
